### ISSUE TITLE
EC Geometry bug?

### ISSUE THREAD

**Issue by forcar** [gemc/detectors#1]
The attached plot shows a missing lead layer between the last two scintillators.  Also the last scintillator (39) does not follow the truncated pyramid geometry and looks almost identical to 38.  In between 38 and 39 there is no lead.  It may be the lead sequence is staggered upward since in EC there is no lead in front of the first scintillator.  I checked Gerry Gilfoyle's old talks and he had it correct in the original GEMC.
- Cole Smith

Addendum: Found bug in detectors/clas12/ec/geometry.pl in build_scintlayers subroutine where the loop index $i is not initialized to 1 for sectors 2-6.  This caused the first scintillator to be inserted with i=40, in effect putting scintillator 1 just below scintillator 39 as seen in the GEMC view (below, bottom).  This also explains why the average energy in the U strips was smaller than V or W since 20% of the energy was missing (plot just below left=U right=W).

I propose putting the statement "my $i = 1;" at line 368 in build_scintlayers.
- Cole Smith

![uv-gemc-muon](https://cloud.githubusercontent.com/assets/10797791/9024021/4444ed40-3884-11e5-8837-a420d0958fa0.png)

![ecstack5](https://cloud.githubusercontent.com/assets/10797791/9016168/cfc61486-379c-11e5-88c6-059eeccc6b3f.png)

**Comment by maureeungaro** [comment]
Testing "New Issue" comments feature. 

This looks like a bug in the geometry. Please modify as needed.
