### ISSUE TITLE
ATOF and AHDC geometry implementation for A Low Energy Recoil Tracker (ALERT)

### ISSUE THREAD

**Issue by Viktoriya89** [gemc/detectors#159]
This issue is to share the implementation of ALERT detector geometry. The detector consists of 2 parts: the hyperbolic drift chamber (AHDC) and time of flight scintillators (ATOF). Now, all active cells geometry is implemented. Any inert material structure can be added later using groovy or perl scripts.

**Comment by maureeungaro** [comment]
merged
